*       soft    core    unlimited
*       hard    core    unlimited
root    soft    core    unlimited
root    hard    core    unlimited
atf     soft    core    unlimited
atf     hard    core    unlimited
slurm   soft    core    unlimited
slurm   hard    core    unlimited
*       soft    memlock unlimited
*       hard    memlock unlimited
root    soft    memlock unlimited
root    hard    memlock unlimited
atf     soft    memlock unlimited
atf     hard    memlock unlimited
slurm   soft    memlock unlimited
slurm   hard    memlock unlimited
