AuthType=auth/munge
AuthAltParameters=jwt_key=/opt/slurm-atf/install/etc/jwt_hs256.key
DbdHost=localhost
SlurmUser=slurm
DebugLevel=info
LogFile=/var/log/slurm-atf/slurmdbd.log
PidFile=/run/slurm-atf/slurmdbd.pid

StorageType=accounting_storage/mysql
StorageHost=localhost
StoragePort=3306
StorageUser=slurm
StorageLoc=slurm_acct_db
