name: Build mock packages

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build for ${{ matrix.platform }}
    permissions:
      contents: write  # for softprops/action-gh-release to create GitHub release
    runs-on: ${{ matrix.runner }}

    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
        include:
          - platform: linux/amd64
            runner: X64
          - platform: linux/arm64
            runner: ARM64

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0

      - name: Build docker images
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          file: cuda-mock-packages/Dockerfile
          push: false
          tags: cuda_mock_builder:0.0.1
          platforms: ${{ matrix.platform }}
          load: true
          build-args: |
            BASE_IMAGE=ubuntu:jammy

      - name: Create cuda_mock_build_output directory
        run: mkdir -p cuda_mock_build_output

      - name: Run Docker container and copy files
        run: |
          container_id=$(docker create cuda_mock_builder:0.0.1)
          docker start $container_id
          docker cp $container_id:/cuda-mock-packages/ ./cuda_mock_build_output/
          docker stop $container_id
          docker rm $container_id

      - name: Create GitHub Release and Upload DEB packages
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: cuda_mocks
          name: Cuda mock packages
          body: "Mock packages for nvidia-open and cuda-drivers"
          draft: false
          prerelease: false
          files: |
            cuda_mock_build_output/cuda-mock-packages/*.deb

      - name: Cleanup
        run: rm -rf cuda_mock_build_output
