name: Build cuda samples binaries

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build for ${{ matrix.platform }}
    permissions:
      contents: write  # for softprops/action-gh-release to create GitHub release
    runs-on: ${{ matrix.runner }}

    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
        build:
          - cuda_version: 12.9.0
            build_args: []
        distribution:
          - ubuntu24.04
        include:
          - platform: linux/amd64
            runner: X64
          - platform: linux/arm64
            runner: ARM64


    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Set lowercase arch var
        run: echo "ARCH=$(echo '${{ matrix.runner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build docker images
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          file: cuda-samples/Dockerfile
          push: false
          tags: cuda_samples_builder:${{ matrix.build.cuda_version }}_${{ matrix.distribution }}
          platforms: ${{ matrix.platform }}
          load: true
          build-args: |
            ${{ matrix.build.build_args }}
            ARCH=${{ env.ARCH }}
          cache-from: type=local,src=.buildx-cache
          cache-to: type=local,dest=.buildx-cache,mode=max

      - name: Create cuda_samples_build_output directory
        run: mkdir -p cuda_samples_build_output

      - name: Run Docker container and copy files
        run: |
          echo "Creating container for image: cuda_samples_builder:${{ matrix.build.cuda_version }}_${{ matrix.distribution }}"
          container_id=$(docker create cuda_samples_builder:${{ matrix.build.cuda_version }}_${{ matrix.distribution }})
          
          docker start $container_id
          
          echo "Copying /usr/src/cuda-samples-${ARCH}.tar.gz"
          docker cp "$container_id:/usr/src/cuda-samples-${ARCH}.tar.gz" ./cuda_samples_build_output/
          
          docker stop $container_id
          docker rm $container_id
        env:
          ARCH: ${{ env.ARCH }}

      - name: Create GitHub Release and Upload cuda samples
        uses: softprops/action-gh-release@6cbd405e2c4e67a21c47fa9e383d020e4e28b836 # v2.3.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: cuda_samples_${{ matrix.build.cuda_version }}_${{ matrix.distribution }}
          name: Cuda samples for cuda ${{ matrix.build.cuda_version }} and ${{ matrix.distribution }}
          draft: false
          prerelease: false
          files: |
            cuda_samples_build_output/cuda-samples-${{ env.ARCH }}.tar.gz

      - name: Cleanup
        run: rm -rf cuda_samples_build_output/*.tar.gz
